minimum_pre_commit_version: 4.6.1

fail_fast: false
files: ''
exclude: ^$

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.0
    hooks:
      - id: uv-lock
      - id: uv-export
      - id: uv-sync
        args: ["--all-groups"]
        stages: [post-checkout, post-merge, post-rewrite]
      # - id: pip-compile
      #   name: pip-compile requirements.in
      #   args: [ requirements.in, -o, requirements.txt ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 1.1.1
    hooks:
      - id: pyrefly-check
        pass_filenames: false
        additional_dependencies: [ ]