site_name: decorator-utils docs
site_author: stickm4n
copyright: 2024, stickm4n

repo_url: https://github.com/stickm4n/decorator-utils

theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    scheme: slate
    primary: black
    accent: blue
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - gen-files:
      scripts:
        - docs/generate_docs.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
