[project]
name = 'decorator-utils'
version = '2.0.0'
description = 'Simple and useful decorator utilities.'

requires-python = '>=3.10'

authors = [
    { name = 'Julio C. Galindo', email = 'jcgalindo.jcgh@gmail.com' },
]
maintainers = []


classifiers = [
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]
keywords = ['decorator', 'utilities']

readme = { file = 'README.md', content-type = 'text/markdown' }
license = { file = 'LICENSE' }

[project.urls]
Repository = 'https://github.com/stickm4n/decorator-utils'
Documentation = 'https://github.com/stickm4n/decorator-utils/wiki'
Issues = 'https://github.com/stickm4n/decorator-utils/issues'

[project.scripts]
#:null:

[project.gui-scripts]
#:null:


[build-system]
requires = ['uv_build~=0.12.0']
build-backend = 'uv_build'


dependencies = []
optional-dependencies = { }

[dependency-groups]
dev = [
    'pre-commit~=4.6.1',
    { include-group = 'lint' },
    { include-group = 'test' }
]
lint = ['ruff~=0.16.0', 'pyrefly~=1.1.1']
test = ['pytest~=9.1.1']
docs = ['mkdocs-gen-files~=0.6.1']


[tool.uv]
conflicts = []
default-groups = []
#:deprecated: dev-dependencies = []
environments = []
managed = true
package = true
required-environments = []
sources = { }

[tool.uv.dependency-groups]
#:null:

[tool.uv.build-backend]
data = { }
default-excludes = true
module-name = 'decorator_utils'
module-root = '.'
namespace = false
source-exclude = []
source-include = []
wheel-exclude = []

[tool.uv.workspace]
exclude = []
members = []
